org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36

# Use Android Studio JBR
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.caching=true
org.gradle.parallel=true

# Skip dependency version checks in Flutter Gradle Plugin
skipDependencyChecks=true
android.skipBuildDependencyValidation=true

# Disable incremental compilation to avoid cross-drive/lock issues
kotlin.incremental=true
kotlin.incremental.js=true
kotlin.incremental.multiplatform=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
