org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# 1. Fix "different roots" errors between C: and D: drives
kotlin.incremental=false
kotlin.incremental.js=false
kotlin.incremental.multiplatform=false

# 2. Force Gradle and Android to use a local folder on the D: drive
# This bypasses permission and lock issues on the C: drive profile
# android.user.home=D:\\.android_local
# gradle.user.home=D:\\.gradle_local
