sonar.projectKey=Sreyneathkaem_voatmean
sonar.organization=sreyneathkaem
sonar.projectName=voatmean

# Analysis starts at the backend directory for now
sonar.sources=backend
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=backend/node_modules/**, backend/test/**
