sonar.projectKey=Sreyneathkaem_voatmean
sonar.organization=sreyneathkaem
sonar.projectName=voatmean

sonar.sources=backend/src
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=backend/node_modules/**, backend/coverage/**, backend/src/**/*.test.js

# Exclude legacy EduAttend files from duplication checks to focus on new model
sonar.cpd.exclusions=backend/src/controllers/admin.controller.js, backend/src/controllers/attendance.controller.js, backend/src/controllers/score.controller.js
