// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbsGLdz1zJ1L7AUM8leLCU0RQ9WEMPQc',
    appId: '1:119959634609:android:2da0d2ef5b60dbd1575890',
    messagingSenderId: '119959634609',
    projectId: 'testing-flutter-3037f',
    storageBucket: 'testing-flutter-3037f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDssIaGb-9rOArZEwlQVILJ2rwDMsmGU',
    appId: '1:119959634609:ios:0795bb4b8bba89c7575890',
    messagingSenderId: '119959634609',
    projectId: 'testing-flutter-3037f',
    storageBucket: 'testing-flutter-3037f.firebasestorage.app',
    iosBundleId: 'kh.edu.camtech.voatmean.voatmeanMobile',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIxxK70sBKrurQU4bW7KKZbWfh9O0PQIg',
    appId: '1:119959634609:web:a7afcf0d22f1dada575890',
    messagingSenderId: '119959634609',
    projectId: 'testing-flutter-3037f',
    authDomain: 'testing-flutter-3037f.firebaseapp.com',
    storageBucket: 'testing-flutter-3037f.firebasestorage.app',
    measurementId: 'G-Q1L6S8NZS8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDssIaGb-9rOArZEwlQVILJ2rwDMsmGU',
    appId: '1:119959634609:ios:0795bb4b8bba89c7575890',
    messagingSenderId: '119959634609',
    projectId: 'testing-flutter-3037f',
    storageBucket: 'testing-flutter-3037f.firebasestorage.app',
    iosBundleId: 'kh.edu.camtech.voatmean.voatmeanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIxxK70sBKrurQU4bW7KKZbWfh9O0PQIg',
    appId: '1:119959634609:web:c7234c98baf313a1575890',
    messagingSenderId: '119959634609',
    projectId: 'testing-flutter-3037f',
    authDomain: 'testing-flutter-3037f.firebaseapp.com',
    storageBucket: 'testing-flutter-3037f.firebasestorage.app',
    measurementId: 'G-MWXY1WL9N6',
  );
}
